exports.seed = (knex, __) => knex('questions')
  .del()
  .then(() => knex('questions').insert([
    {
      question_position: 1,
      question_name: 'Vilket datum önskar du att er vigsel äger rum?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 7,
    },
    {
      question_position: 2,
      question_name: 'Vilket datum skulle passa dig bättre?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 3,
    },
    {
      question_position: 3,
      question_name: 'Har ni intyg för hindersprövning?',
      question_description: 'Läs mer om hindersprövning här "länk"',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      option_group_id: 1,
      question_type: 10,
    },
    {
      question_position: 4,
      question_name: 'Hur många gäster kommer nävara under vigseln?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      option_group_id: 4,
      question_type: 10,
    },
    {
      question_position: 5,
      question_name: 'Vad heter ditt vittne i förnamn?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
    {
      question_position: 6,
      question_name: 'Vad heter ditt vittne i efternamn?',
      question_description: '',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
    {
      question_position: 7,
      question_name: 'Vilken address har ditt vittne?',
      question_description: '',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
    {
      question_position: 8,
      question_name: 'Vilket postnummer har ditt vittne?',
      question_description: '',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 6,
    },
    {
      question_position: 9,
      question_name: 'Bor ditt vittne i Sverige',
      question_description: '',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 7,
    },
    {
      question_position: 10,
      question_name: 'Vilken ort bor ditt vittne på?',
      question_description: '',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
    {
      question_position: 11,
      question_name: 'Vilken land kommer ditt vittne ifrån?',
      question_description: '',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 12,
    },
    {
      question_position: 12,
      question_name: 'Vad heter din partners vittne i förnamn?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 7,
    },
    {
      question_position: 13,
      question_name: 'Vad heter din partners vittne i efternamn?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 7,
    },
    {
      question_position: 14,
      question_name: 'Vilken address har din partners vittne?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 7,
    },
    {
      question_position: 15,
      question_name: 'Vilket postnummer har din partners vittne?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 6,
    },
    {
      question_position: 16,
      question_name: 'Bor din partners vittne i Sverige',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 7,
    },
    {
      question_position: 17,
      question_name: 'Vilken ort bor din partners vittne på?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
    {
      question_position: 18,
      question_name: 'Vilken land kommer din partners vittne ifrån?',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 12,
    },
    {
      question_position: 19,
      question_name: 'Vad är din partners personnummer? ',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 6,
    },
    {
      question_position: 20,
      question_name: 'Vad är din partners förnamn? ',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
    {
      question_position: 21,
      question_name: 'Vad är din partners efternamn? ',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
    {
      question_position: 22,
      question_name: 'Vad är din partners nuvarande adress? ',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
    {
      question_position: 23,
      question_name: 'Vad är din partners postnummer? ',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 6,
    },
    {
      question_position: 24,
      question_name: 'I vilken ort bor din partner? ',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 12,
    },
    {
      question_position: 25,
      question_name: 'Har ni några överiga önskemål gällande vigseln?',
      question_required: false,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 9,
    },
  ]));
