
exports.seed = (knex, __) => knex('validations')
  .del()
  .then(() => knex('validations').insert([
    {
      name: 'is_email_input',
      type: 'default',
      method: 'isEmail',
      args: JSON.stringify({}),
      message: 'Den email du har angivit är inte korrekt',
      validWhen: true,
    },
    {
      name: 'is_empty_input',
      type: 'default',
      method: 'isEmpty',
      args: JSON.stringify({}),
      message: 'Fältet får inte vara tomt',
      validWhen: false,
    },
    {
      name: 'is_max_length_text_input',
      type: 'default',
      method: 'isLength',
      args: JSON.stringify({ min: 100 }),
      message: 'Ditt svar är längre än 100 tecken',
      validWhen: true,
    },
    {
      name: 'is_min_length_text_input',
      type: 'default',
      method: 'isLength',
      args: JSON.stringify({ min: 2 }),
      message: 'Ditt svar är för kort',
      validWhen: true,
    },
    {
      name: 'is_min_length_textarea',
      type: 'default',
      method: 'isLength',
      args: JSON.stringify({ min: 2 }),
      message: 'Ditt svar är för kort',
      validWhen: true,
    },
    {
      name: 'is_max_length_textarea',
      type: 'default',
      method: 'isLength',
      args: JSON.stringify({ min: 300 }),
      message: 'Ditt svar är längre än 300 tecken',
      validWhen: true,
    },
    {
      name: 'is_numeric_input',
      type: 'default',
      method: 'isNumeric',
      args: JSON.stringify({}),
      message: 'Endast nummer är tillåtna',
      validWhen: true,
    },
    {
      name: 'is_alpha_text_input',
      type: 'default',
      method: 'isAlpha',
      args: JSON.stringify({}),
      message: 'Endast bokstäver är tillåtna',
      validWhen: true,
    },
    {
      name: 'is_after_date',
      type: 'default',
      method: 'isAlpha',
      args: JSON.stringify({}),
      message: 'Ange ett senare datum',
      validWhen: true,
    },
    {
      name: 'is_one_choice_select',
      type: 'default',
      method: 'isLength',
      message: 'Endast ett val är tillåtet',
      args: JSON.stringify({ min: 1, max: 1 }),
      validWhen: true,
    },
  ]));
