exports.seed = (knex, __) => knex('questions')
  .del()
  .then(() => knex('questions').insert([
    {
      question_position: 1,
      question_name: 'Vem ska du gifta dig med?',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'text',
    },
    {
      question_position: 2,
      question_name: 'Vad har din;/text:1:;för personnummer?',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'number',
    },
    {
      question_position: 3,
      question_name: 'Bor din;/text:1:;på samma adress som du? ',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'radio',
    },
    {
      question_position: 4,
      question_name: 'Vilken adress bor din;/text:1:;för nuvarande på? ',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'text',
    },
    {
      question_position: 5,
      question_name: 'Vilket postnummer har din;/text:1:;',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'text',
    },
    {
      question_position: 6,
      question_name: 'Vilken ort bor din;/text:1:;på?',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'text',
    },
    {
      question_position: 7,
      question_name: 'Var vill ni gifta er?',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'radio',
    },
    {
      question_position: 8,
      question_name: 'Vilken annan plats vill ni gifta er på?',
      question_placeholder: 'Ange en annan plats',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'text',
    },
    {
      question_position: 9,
      question_name: 'När vill ni gifta er?',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'datetime',
    },
    {
      question_position: 10,
      question_name: 'Ni behöver ha två vittnen under er vigsel. Har ni bestämt vilka vittnen ni vill ha? ',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'radio',
    },
    {
      question_position: 11,
      question_name: 'Okej, då kan ni komplettera det senare.',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'info',
    },
    {
      question_position: 12,
      question_name: 'Vad heter ert första vittne?',
      question_info: 'Under vigseln behöver ni ha två vittnen. För att jag ska kunna boka er vigsel behöver jag några uppgifter om dem.',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'text',
    },
    {
      question_position: 13,
      question_name: 'Vad heter ert andra vittne?',
      question_placeholder: 'Test placeholder',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'text',
    },
    {
      question_position: 14,
      question_name: 'Hur många gäster kommer till er vigsel?',
      question_placeholder: 'Test placeholder',
      question_description: 'I Rådhusets vigselsal får det max vara 20 personer samtidigt. Ni kan därför som mest ha 17 gäster till er vigsel, inklusive barn och era vittnen.',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'number',
    },
    {
      question_position: 15,
      question_name: 'Har ni några speciella önskemål för er vigsel?',
      question_placeholder: 'Test placeholder',
      question_description: 'Det kan till exempel vara val av vigselförrättare.',
      question_required: false,
      question_multiple_answers: false,
      form_id: 1,
      question_type: 'text',
    },
    {
      question_position: 16,
      question_info: 'Innan ni gifter er måste Skatteverket intyga att det inte finns några hinder för giftermål.',
      question_placeholder: 'Test placeholder',
      question_name: 'Har ni intyg för hindersprövning från Skatteverket?',
      question_info:'Innan ni gifter er måste Skatteverket göra en hindersprövning, för att se till att det inte finns några hinder för äktenskapet. Ni ansöker om hindersprövning genom att fylla i en blankett som ni skickar till Skatteverket. Du hittar blanketten, och mer information om hindersprövning, på Skatteverkets webbplats.',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      option_group_id: 1,
      question_type: 'radio',
    },
    {
      question_position: 17,
      question_placeholder: 'Test placeholder',
      question_name: 'Ni ansöker om hindersprövning på [Skatteverkets webbplats.]',
      question_required: true,
      question_multiple_answers: false,
      form_id: 1,
      option_group_id: 1,
      question_type: 'info',
    },
  ]));
