
exports.seed = (knex, __) => knex('option_choices')
  .del()
  .then(() => knex('option_choices').insert([
    { option_group_id: 1, option_choice_name: 'Ja', option_choice_value: 'yes' },
    { option_group_id: 1, option_choice_name: 'Nej', option_choice_value: 'no' },
    { option_group_id: 2, option_choice_name: '1', option_choice_value: '1' },
    { option_group_id: 2, option_choice_name: '2', option_choice_value: '2' },
    { option_group_id: 2, option_choice_name: '3', option_choice_value: '3' },
    { option_group_id: 2, option_choice_name: '4', option_choice_value: '4' },
    { option_group_id: 2, option_choice_name: '5', option_choice_value: '5' },
    { option_group_id: 3, option_choice_name: '1', option_choice_value: '1' },
    { option_group_id: 3, option_choice_name: '2', option_choice_value: '2' },
    { option_group_id: 3, option_choice_name: '3', option_choice_value: '3' },
    { option_group_id: 3, option_choice_name: '4', option_choice_value: '4' },
    { option_group_id: 3, option_choice_name: '5', option_choice_value: '5' },
    { option_group_id: 3, option_choice_name: '6', option_choice_value: '6' },
    { option_group_id: 3, option_choice_name: '7', option_choice_value: '7' },
    { option_group_id: 3, option_choice_name: '8', option_choice_value: '8' },
    { option_group_id: 3, option_choice_name: '9', option_choice_value: '9' },
    { option_group_id: 3, option_choice_name: '10', option_choice_value: '10' },
    { option_group_id: 4, option_choice_name: 'Inga', option_choice_value: 'none' },
    { option_group_id: 4, option_choice_name: '1-3', option_choice_value: '1-3' },
    { option_group_id: 4, option_choice_name: '4-6', option_choice_value: '4-6' },
    { option_group_id: 4, option_choice_name: '7-9', option_choice_value: '7-9' },
    { option_group_id: 4, option_choice_name: '10-12', option_choice_value: '10-12' },
    { option_group_id: 4, option_choice_name: '13-15', option_choice_value: '13-15' },
    { option_choice_name: 'Rådhuset', option_choice_value: 'radhuset' },
    { option_choice_name: 'Annan plats', option_choice_value: 'other place'},
  ]));
